# Generated by Django 3.2.9 on 2021-11-22 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211122_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='webData',
            fields=[
                ('monitored', models.BooleanField(default=True)),
                ('timePeriod', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(2)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.website')),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='owner',
            field=models.ManyToManyField(through='base.webData', to='base.Profile'),
        ),
    ]
