# Generated by Django 3.2.9 on 2021-11-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211122_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='webData',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='base.webdata'),
            preserve_default=False,
        ),
    ]
