# Generated by Django 3.2.9 on 2021-11-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_history_webdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='website',
        ),
    ]
