# Generated by Django 3.2.9 on 2021-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_history_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='webdata',
            unique_together={('website', 'profile')},
        ),
    ]
